<a href="https://colab.research.google.com/github/MorshedulHoque/Encoding-Categorical-Data/blob/main/Encoding_Categorical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/customer.csv')

In [4]:
df.sample(5)

age  gender   review education purchased
43   27    Male     Poor        PG        No
3    72  Female     Good        PG        No
35   74    Male     Poor    School       Yes
20   57  Female  Average    School       Yes
23   96  Female     Good    School        No

In [7]:
df = df[['review', 'education', 'purchased']]

In [8]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[['review', 'education']], df['purchased'], test_size=0.3)

In [12]:
X_train

review education
0   Average    School
46     Poor        PG
3      Good        PG
33     Good        PG
31     Poor    School
34  Average    School
4   Average        UG
35     Poor    School
47     Good        PG
16     Poor        UG
25     Good    School
18     Good    School
29  Average        UG
39     Poor        PG
8   Average        UG
17     Poor        UG
12     Poor    School
37  Average        PG
19     Poor        PG
28     Poor    School
26     Poor        PG
36     Good        UG
41     Good        PG
48     Good        UG
6      Good    School
15     Poor        UG
30  Average        UG
24  Average        PG
7      Poor    School
9      Good        UG
49     Good        UG
2      Good        PG
43     Poor        PG
1      Poor        UG
13  Average    School

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [14]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [15]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [16]:
X_train = oe.transform(X_train)

In [17]:
X_train

array([[1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.]])

In [18]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [19]:
X_train

array([[1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 2.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 1.],
       [1., 0.]])

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le = LabelEncoder()

In [22]:
le.fit(y_train)

LabelEncoder()

In [23]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [24]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [25]:
y_train

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0])